from enum import Enum


MAX_NUMBER_OF_PLAYERS: int = 4

PLAYER_INPUT_TYPE_COMPUTER: int = 0xff

class GamePlayLevel(Enum):
	GAME_PLAY_LEVEL_BEGINNER:   int = 0
	GAME_PLAY_LEVEL_STANDARD:   int = 1
	GAME_PLAY_LEVEL_TOURNAMENT: int = 2

class SpeciesId(Enum):
	SPECIES_ID_MECHTRON:   int = 0
	SPECIES_ID_GOLLUMER:   int = 1
	SPECIES_ID_PACKER:     int = 2
	SPECIES_ID_BONZOID:    int = 3
	SPECIES_ID_SPHEROID:   int = 4
	SPECIES_ID_FLAPPER:    int = 5
	SPECIES_ID_LEGGITE:    int = 6
	SPECIES_ID_HUMANOID:   int = 7
NUMBER_OF_SPECIES_IDS: int = 8

PLANET_PLOT_WIDTH:  int = 9
PLANET_PLOT_HEIGHT: int = 5
PLANET_NUMBER_OF_PLOTS: int= PLANET_PLOT_WIDTH * PLANET_PLOT_HEIGHT # 45
PLOT_INDEX_TOWN: int = 22

PLOT_UNOWNED: int = 0xff

class GoodType(Enum):
	GOOD_TYPE_NONE:       int = 0xff
	GOOD_TYPE_FOOD:       int = 0
	GOOD_TYPE_ENERGY:     int = 1
	GOOD_TYPE_SMITHORE:   int = 2
	GOOD_TYPE_CRYSTITE:   int = 3
	GOOD_TYPE_MULE:       int = 4
	GOOD_TYPE_LAND:       int = 5
NUMBER_OF_GOOD_TYPES: int = 4

class PlotType(Enum):
	PLOT_TYPE_UNUSED:     int = 0
	PLOT_TYPE_FOOD:       int = 1 #GoodType.GOOD_TYPE_FOOD + 1
	PLOT_TYPE_ENERGY:     int = 2 #GoodType.GOOD_TYPE_ENERGY + 1
	PLOT_TYPE_SMITHORE:   int = 3 #GoodType.GOOD_TYPE_SMITHORE + 1
	PLOT_TYPE_CRYSTITE:   int = 4 #GoodType.GOOD_TYPE_CRYSTITE + 1
NUMBER_OF_PLOT_TYPES: int = 5 #PLOT_TYPE_CRYSTITE + 1

PlotTypeToGoodType: dict[PlotType, GoodType] = {
	PlotType.PLOT_TYPE_UNUSED:   GoodType.GOOD_TYPE_NONE,
	PlotType.PLOT_TYPE_FOOD:     GoodType.GOOD_TYPE_FOOD,
	PlotType.PLOT_TYPE_ENERGY:   GoodType.GOOD_TYPE_ENERGY,
	PlotType.PLOT_TYPE_SMITHORE: GoodType.GOOD_TYPE_SMITHORE,
	PlotType.PLOT_TYPE_CRYSTITE: GoodType.GOOD_TYPE_CRYSTITE
}

GoodTypeToPlotType: dict[GoodType, PlotType] = {
	GoodType.GOOD_TYPE_NONE:     PlotType.PLOT_TYPE_UNUSED,
	GoodType.GOOD_TYPE_FOOD:     PlotType.PLOT_TYPE_FOOD,
	GoodType.GOOD_TYPE_ENERGY:   PlotType.PLOT_TYPE_ENERGY,
	GoodType.GOOD_TYPE_SMITHORE: PlotType.PLOT_TYPE_SMITHORE,
	GoodType.GOOD_TYPE_CRYSTITE: PlotType.PLOT_TYPE_CRYSTITE
}

class BaseProduction(Enum):
	BASE_PRODUCTION_NO:        int = 0 # NOTE: Not using BASE_PRODUCTION_NONE (different values).
	BASE_PRODUCTION_LOW:       int = 1
	BASE_PRODUCTION_MEDIUM:    int = 2
	BASE_PRODUCTION_HIGH:      int = 3
	BASE_PRODUCTION_VERY_HIGH: int = 4
	BASE_PRODUCTION_UNKNOWN:   int = 0x80
	BASE_PRODUCTION_NONE:      int = 0xff

NUMBER_OF_ROUND_EVENT_IDS:       int = 8 #ROUND_EVENT_ID_FIRE_IN_STORE + 1
class RoundEventId(Enum):
	ROUND_EVENT_ID_PEST_ATTACK:      int = 0
	ROUND_EVENT_ID_PIRATE_SHIP:      int = 1
	ROUND_EVENT_ID_ACID_RAIN_STORM:  int = 2
	ROUND_EVENT_ID_PLANET_QUAKE:     int = 3
	ROUND_EVENT_ID_SUNSPOT_ACTIVITY: int = 4
	ROUND_EVENT_ID_METEORITE_STRIKE: int = 5
	ROUND_EVENT_ID_RADIATION:        int = 6
	ROUND_EVENT_ID_FIRE_IN_STORE:    int = 7
	ROUND_EVENT_ID_TRANSPORT_SHIP_ARRIVES: int = 9 #NUMBER_OF_ROUND_EVENT_IDS + 0
	ROUND_EVENT_ID_TRANSPORT_SHIP_LEAVES:  int = 10 #NUMBER_OF_ROUND_EVENT_IDS + 1
	ROUND_EVENT_ID_TRANSPORT_SHIP_RETURNS: int = 11 #NUMBER_OF_ROUND_EVENT_IDS + 2

class TurnEventId(Enum):
	TURN_EVENT_ID_HOME_PACKAGE:       int = 0
	TURN_EVENT_ID_SPACE_TRAVELER:     int = 1
	TURN_EVENT_ID_GLAC_ELVES:         int = 2
	TURN_EVENT_ID_MULE_BEST_BUILT:    int = 3
	TURN_EVENT_ID_MULE_LOST_BOLT:     int = 4
	TURN_EVENT_ID_MULE_TAP_DANCING:   int = 5
	TURN_EVENT_ID_MINING_MULES:       int = 6
	TURN_EVENT_ID_SOLAR_COLLECTORS:   int = 7
	TURN_EVENT_ID_AGR_COUNCIL:        int = 8
	TURN_EVENT_ID_WART_WORM:          int = 9
	TURN_EVENT_ID_ANTIQUE_COMPUTER:   int = 10
	TURN_EVENT_ID_SWAMP_EEL_EATING:   int = 11
	TURN_EVENT_ID_HOME_CHARITY:       int = 12
	TURN_EVENT_ID_AD_INVESTMENTS:     int = 13
	TURN_EVENT_ID_RELATIVE_DIED:      int = 14
	TURN_EVENT_ID_DEAD_MOOSE_RAT:     int = 15
	TURN_EVENT_ID_GYPSY_INLAWS:       int = 16
	TURN_EVENT_ID_FLYING_CAT_BUGS:    int = 17
	TURN_EVENT_ID_TWO_LEGGED_KAZINGA: int = 18
	TURN_EVENT_ID_BAT_LIZARD_BITE:    int = 19
	TURN_EVENT_ID_LOST_PLOT:          int = 20
	TURN_EVENT_ID_RECEIVED_PLOT:      int = 21

class GameScoreRating(Enum):
	GAME_SCORE_RATING_NO_ENERGY:           int = -2
	GAME_SCORE_RATING_NO_FOOD:             int = -1
	GAME_SCORE_RATING_FAILED_DISMALLY:     int = 0
	GAME_SCORE_RATING_FAILED:              int = 1
	GAME_SCORE_RATING_SURVIVED:            int = 2
	GAME_SCORE_RATING_SUCCEEDED_MINIMUM:   int = 3
	GAME_SCORE_RATING_SUCCEEDED_PLEASED:   int = 4
	GAME_SCORE_RATING_SUCCEEDED_EXTREMELY: int = 5
	GAME_SCORE_RATING_SUCCEEDED_DELIGHTED: int = 6
